### ISSUE TITLE
[Bug]: It doesn't work when blade file is not in `resources/view/livewire`

### ISSUE THREAD

**Issue by AamirSohailKmAs** [bebo925/livewire-switcher#1]

**Comment by bebo925** [comment]
I am not sure of a good way to find the related file when it doesn't follow the default Livewire conventions.  I might have some time to look it over in the next week.

Would love any suggestions or PR's.

**Comment by AamirSohailKmAs** [comment]
I'll try, I have a rough idea about this issue.
